# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Manga' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Manga

  target 'Manga-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

    pod 'CodePush', :path => '../node_modules/react-native-code-push'

  end

  target 'MangaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end