# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Manga' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Manga

  target 'Manga-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MangaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Manga-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Manga-tvOS


end
